BestDjango/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.accounts import urls as accounts_urls
from apps.core import urls as core_urls
from apps.tasks import urls as tasks_urls
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(core_urls, namespace='core')),
    path('tasks/', include(tasks_urls, namespace='tasks')),
    path('accounts/', include(accounts_urls, namespace='accounts')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('add-user/', views.add_user, name='add_user'),
    path('change-user/<str:username>/', views.change_user, name='change_user'),
    path('change-user/', views.change_user, name='change_user'),
    path('login-user/', views.login_user, name='login_user'),
    path('logout-user/', views.logout_user, name='logout_user'),
    path('change-password-user/', views.change_password_user, name='change_password_user'),
    path('profile-user/<str:username>/', views.profile_user, name='profile_user'),
    path('profile-user/', views.profile_user, name='profile_user'),
    path('my-profile-user/', views.list_profile_user, name='list_profile_user'),
]

apps/accounts/models.py
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.conf import settings


# Create your models here.
class UserProfile(models.Model):
    photo = models.ImageField(_('Photo'), upload_to='photos')
    cell_phone = models.CharField(_('Cell Phone'), max_length=16)
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    active_language = models.CharField(
        max_length=10,
        choices=settings.LANGUAGES,
        default=settings.LANGUAGE_CODE,
        verbose_name=_("Active Language")
    )

    def __str__(self):
        return '{} - {}'.format(self.user.username, self.cell_phone)

    def clean(self):
        model = self.__class__
        if model.objects.count() > 0 and self.id != model.objects.get().id:
            raise ValidationError(_("Registered profile already exists."))

    class Meta:
        verbose_name = _('User Profile')
        verbose_name_plural = _('User Profiles')

apps/accounts/views.py
# DJANGO IMPORTS
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.contrib import messages
from django.utils.translation import gettext_lazy as _

# PROJECT IMPORTS
from .form import UserForm, UserProfileForm, ChangeUserForm
from .models import UserProfile


def add_user(request):
    template_name = 'accounts/add_user.html'
    form = UserForm()
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            f = form.save(commit=False)
            f.set_password(f.password)
            f.save()
            messages.success(request, _('Saved successfully!'))
            return redirect('core:home')
        messages.error(request, form.errors)
    context = {'form': form}
    return render(request, template_name, context)


def login_user(request):
    template_name = 'accounts/login_user.html'

    if request.POST:
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect(request.GET.get('next', '/'))
        else:
            messages.error(request, _('Username or Password incorrect!'))

    return render(request, template_name, {})


@login_required(login_url='/accounts/login-user')
def logout_user(request):
    logout(request)
    return redirect('accounts:login_user')


@login_required(login_url='/accounts/login-user')
def change_password_user(request):
    template_name = 'accounts/change_password_user.html'
    form = PasswordChangeForm(user=request.user)

    if request.method == 'POST':
        form = PasswordChangeForm(user=request.user, data=request.POST)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            messages.success(request, _('Change password successfully!'))
        else:
            messages.error(request, _('Not possible change password!'))
            messages.error(request, form.errors)

    context = {'form': form}
    return render(request, template_name, context)


@login_required(login_url='/accounts/login-user')
def list_profile_user(request):
    template_name = 'accounts/list_profile_user.html'
    try:
        profile = UserProfile.objects.get(user=request.user)
    except UserProfile.DoesNotExist:
        profile = None
    context = {'profile': profile}
    return render(request, template_name, context)


@login_required(login_url='/accounts/login-user')
def profile_user(request, username: str = None):
    """
        View to add and change userprofile if username exists
    """
    template_name = 'accounts/add_profile_user.html'
    form = UserProfileForm()
    user = None
    if username:
        try:
            user = UserProfile.objects.get(user__username=username)
            form = UserProfileForm(instance=user)
        except UserProfile.DoesNotExist:
            try:
                user = UserProfile.objects.get(user=request.user)
                form = UserProfileForm(instance=user)
            except UserProfile.DoesNotExist:
                pass

    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES, instance=user)

        if form.is_valid():
            f = form.save(commit=False)
            f.user = request.user
            f.save()
            update_session_auth_hash(request, f.user)
            messages.success(request, _('Profile Updated successfully!'))
        else:
            messages.error(request, _('Not possible Updated profile!'))
            messages.error(request, form.errors)

    context = {'form': form}
    return render(request, template_name, context)


@login_required(login_url='/accounts/login-user')
def change_user(request, username: str = None):
    template_name = 'accounts/change_user.html'
    try:
        user = User.objects.get(username=username)
        form = ChangeUserForm(instance=user)
    except UserProfile.DoesNotExist:
        user = request.user
        form = ChangeUserForm(instance=user)

    if request.method == 'POST':
        form = ChangeUserForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            messages.success(request, _('Updated successfully!'))
            return redirect('core:home')
        messages.error(request, form.errors)
    context = {'form': form}
    return render(request, template_name, context)

templates/accounts/add_profile_user.html
{% extends 'base.html' %}
{% load i18n widget_tweaks %}

{% block title %}
    {% trans 'Profile' %} - {{ block.super }}
{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1>{% trans 'Profile' %}</h1>
                {% include 'partials/messages.html' %}
                <form method="POST" action="." enctype="multipart/form-data">
                  {% csrf_token %}
                  <div class="mb-3">
                    <label
                            for="{{ form.photo.id_for_label }}"
                            class="form-label">{% trans 'Photo Profile' %}</label>
                    {{ form.photo|add_class:"form-control-file" }}
                  </div>
                  <div class="mb-3">
                    <label
                            for="{{ form.cell_phone.id_for_label }}"
                            class="form-label">{% trans 'Cell Phone' %}</label>
                    {{ form.cell_phone|add_class:"form-control" }}
                  </div>
                  <div class="mb-3">
                    <label
                            for="{{ form.active_language.id_for_label }}"
                            class="form-label">{% trans 'Active Language' %}</label>
                    {{ form.active_language|add_class:"form-control" }}
                  </div>
                  <button type="submit" class="btn btn-primary">{% trans 'Save' %}</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

templates/accounts/add_user.html
{% extends 'base.html' %}
{% load i18n widget_tweaks %}

{% block title %}
    {% trans 'New User' %} - {{ block.super }}
{% endblock %}

{% block body %}

    <div class="container">
        <div class="row">
            <div class="col-12">
                <h1>{% trans 'New User' %}</h1>
                {% include 'partials/messages.html' %}
                <form method="POST" action=".">
                  {% csrf_token %}
                  <div class="mb-3">
                    <label
                            for="{{ form.first_name.id_for_label }}"
                            class="form-label">{% trans 'First Name' %}</label>
                    {{ form.first_name|add_class:"form-control"|attr:"autofocus" }}
                  </div>
                  <div class="mb-3">
                    <label
                            for="{{ form.last_name.id_for_label }}"
                            class="form-label">{% trans 'Last Name' %}</label>
                    {{ form.last_name|add_class:"form-control" }}
                  </div>
                  <div class="mb-3">
                    <label
                            for="{{ form.username.id_for_label }}"
                            class="form-label">{% trans 'Username' %}</label>
                    {{ form.username|add_class:"form-control" }}
                  </div>
                  <div class="mb-3">
                    <label
                            for="{{ form.email.id_for_label }}"
                            class="form-label">{% trans 'Email' %}</label>
                    {{ form.email|add_class:"form-control" }}
                  </div>
                  <div class="mb-3">
                    <label
                            for="{{ form.password.id_for_label }}"
                            class="form-label">{% trans 'Password' %}</label>
                    {{ form.password|add_class:"form-control"|attr:"type:password" }}
                  </div>
                  <button type="submit" class="btn btn-primary">{% trans 'Save' %}</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

templates/accounts/change_password_user.html
{% extends 'base.html' %}
{% load i18n widget_tweaks %}

{% block title %}
    {% trans 'Change User Password' %} - {{ block.super }}
{% endblock %}

{% block body %}

    <div class="container">
        <div class="row">
            <div class="col-12">
                <h1>{% trans 'Change User Password' %}</h1>
                {% include 'partials/messages.html' %}
                <form method="POST" action=".">
                  {% csrf_token %}
                  <div class="mb-3">
                    <label
                            for="{{ form.old_password.id_for_label }}"
                            class="form-label">{% trans 'Old Password' %}</label>
                    {{ form.old_password|add_class:"form-control"|attr:"type:password" }}
                  </div>
                  <div class="mb-3">
                    <label
                            for="{{ form.new_password1.id_for_label }}"
                            class="form-label">{% trans 'New Password' %}</label>
                    {{ form.new_password1|add_class:"form-control"|attr:"type:password" }}
                  </div>
                  <div class="mb-3">
                    <label
                            for="{{ form.new_password2.id_for_label }}"
                            class="form-label">{% trans 'Confirm New Password' %}</label>
                    {{ form.new_password2|add_class:"form-control"|attr:"type:password" }}
                  </div>
                  <button type="submit" class="btn btn-primary">{% trans 'Save' %}</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

templates/accounts/change_user.html
{% extends 'base.html' %}
{% load i18n widget_tweaks %}

{% block title %}
    {% trans 'Updated User Informations' %} - {{ block.super }}
{% endblock %}

{% block body %}

    <div class="container">
        <div class="row">
            <div class="col-12">
                <h1>{% trans 'Updated User Informations' %}</h1>
                {% include 'partials/messages.html' %}
                <form method="POST" action=".">
                  {% csrf_token %}
                  <div class="mb-3">
                    <label
                            for="{{ form.first_name.id_for_label }}"
                            class="form-label">{% trans 'First Name' %}</label>
                    {{ form.first_name|add_class:"form-control"|attr:"autofocus" }}
                  </div>
                  <div class="mb-3">
                    <label
                            for="{{ form.last_name.id_for_label }}"
                            class="form-label">{% trans 'Last Name' %}</label>
                    {{ form.last_name|add_class:"form-control" }}
                  </div>
                  <div class="mb-3">
                    <label
                            for="{{ form.email.id_for_label }}"
                            class="form-label">{% trans 'Email' %}</label>
                    {{ form.email|add_class:"form-control" }}
                  </div>
                  <button type="submit" class="btn btn-primary">{% trans 'Save' %}</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

templates/accounts/list_profile_user.html
{% extends 'base.html' %}
{% load i18n widget_tweaks %}


{% block title %}
    {% trans 'My Profile' %} - {{ block.super }}
{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
            <h1>{% trans 'My Profile' %}</h1>

            {% if profile %}
                <div class="media">
                    <img src="{{ profile.photo.url }}"
                         class="align-self-start mr-3 rounded-circle"
                         alt="{% trans 'Photo Profile' %}{{ user.get_full_name|default:user.username }}"
                         width="100" height="100">
                    <div class="media-body">
                        <h5 class="mt-0">{{ profile.user.get_full_name }}</h5>
                        <p>{% trans 'Cell Phone' %}: {{ profile.cell_phone }}</p>
                        <p>{% trans 'Email' %}: {{ profile.user.email }}</p>
                    </div>
                </div>
                <a href="{% url 'accounts:profile_user' user.username %}" class="btn btn-primary">
                    {% trans 'Change Profile' %}
                </a>
            {% else %}
                <h2>{% trans "You don't have an updated profile." %}</h2>
                <a href="{% url 'accounts:profile_user' '' %}" class="btn btn-primary">
                    {% trans 'Updated Profile' %}
                </a>
            {% endif %}

            </div>
        </div>
    </div>
{% endblock %}

templates/accounts/login_user.html
{% load i18n static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <title>{% trans 'BestDjango Login' %}</title>

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/sign-in/">
    <!-- Favicons -->
    <meta name="theme-color" content="#712cf9">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/signin.css' %}" rel="stylesheet">
  </head>
  <body class="text-center">

    <main class="form-signin w-100 m-auto">
      {% include 'partials/messages.html' %}
      <form method="POST" action="." autocomplete="off">
        {% csrf_token %}
        <h1 class="h3 mb-3 fw-normal">{% trans 'Login' %}</h1>

        <div class="form-floating">
          <input type="text" class="form-control" id="username"
                 name="username" placeholder="{% trans 'Username' %}" required autofocus>
          <label for="username">{% trans 'Username' %}</label>
        </div>
        <div class="form-floating">
          <input type="password" class="form-control" id="password" name="password"
                 placeholder="{% trans 'Password' %}" required>
          <label for="password">{% trans 'Password' %}</label>
        </div>
        <button class="w-100 btn btn-lg btn-primary" type="submit">{% trans 'Sign in' %}</button>
        <a href="{% url 'accounts:add_user' %}"
                class="w-100 btn btn-lg btn-info">{% trans 'Create User' %}</a>
        <p class="mt-5 mb-3 text-muted">&copy; 2022</p>
      </form>
    </main>

  </body>
</html>