BestDjango/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.accounts import urls as accounts_urls
from apps.core import urls as core_urls
from apps.tasks import urls as tasks_urls
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(core_urls, namespace='core')),
    path('tasks/', include(tasks_urls, namespace='tasks')),
    path('accounts/', include(accounts_urls, namespace='accounts')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('add-user/', views.add_user, name='add_user'),
    path('change-user/<str:username>/', views.change_user, name='change_user'),
    path('change-user/', views.change_user, name='change_user'),
    path('login-user/', views.login_user, name='login_user'),
    path('logout-user/', views.logout_user, name='logout_user'),
    path('change-password-user/', views.change_password_user, name='change_password_user'),
    path('profile-user/<str:username>/', views.profile_user, name='profile_user'),
    path('profile-user/', views.profile_user, name='profile_user'),
    path('my-profile-user/', views.list_profile_user, name='list_profile_user'),
]

apps/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
    path('', views.search_tasks, name='search_tasks'),
]

apps/tasks/urls.py
from django.urls import path
from . import views

app_name = 'tasks'

urlpatterns = [
    # Categories
    path('category/list', views.list_categories, name='list_category'),
    path('category/add', views.add_category, name='add_category'),
    path('category/edit/<int:id_category>/', views.edit_category, name='edit_category'),
    path('category/delete/<int:id_category>/', views.delete_category, name='delete_category'),
    # Tasks
    path('task/list', views.list_tasks, name='list_task'),
    path('task/add', views.add_task, name='add_task'),
    path('task/edit/<int:id_task>/', views.edit_task, name='edit_task'),
    path('task/delete/<int:id_task>/', views.delete_task, name='delete_task'),
]

apps/tasks/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import gettext_lazy as _


# Create your models here.
class Category(models.Model):
    name = models.CharField(_('Name'), max_length=150)
    description = models.TextField(_('Description'), blank=True, null=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name = _('Category')
        verbose_name_plural = _('Categories')
        ordering = ['id']

    def __str__(self):
        return '{} - {}'.format(self.id, self.name)


class Task(models.Model):
    PRIORITY_CHOICES = (
        ('L', _('LOW')),
        ('M', _('MEDIUM')),
        ('H', _('HIGH')),
    )
    STATUS_CHOICES = (
        ('I', _('IN PROGRESS')),
        ('P', _('PENDING')),
        ('C', _('COMPLETED')),
    )
    name = models.CharField(_('Name'), max_length=200)
    description = models.TextField(_('Description'))
    end_date = models.DateField(_('End Date'), auto_now=False, auto_now_add=False)
    priority = models.CharField(_('Priority'), max_length=1, choices=PRIORITY_CHOICES)
    category = models.ManyToManyField(Category)
    status = models.CharField(_('Status'), max_length=1, choices=STATUS_CHOICES)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name = _('Task')
        verbose_name_plural = _('Tasks')
        ordering = ['id']

    def __str__(self):
        return '{} - {}'.format(self.id, self.name)

    def list_categories(self):
        return ', '.join([cat.name for cat in self.category.all()])
    list_categories.short_description = _("Categories")

templates/base.html
{% load static i18n %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/select2.min.css' %}">
        <link rel="stylesheet" href="//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
{#        <link rel="stylesheet" href="/resources/demos/style.css">#}

        <meta charset="UTF-8">
        <title>{% block title %}BestDjango{% endblock title %}</title>
    </head>
    <body>

        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-xl">
              <a class="navbar-brand" href="{% url 'core:home' %}">{% trans 'Best Django' %}</a>
              <button
                      class="navbar-toggler"
                      type="button"
                      data-bs-toggle="collapse"
                      data-bs-target="#navbarMenu"
                      aria-controls="navbarMenu"
                      aria-expanded="false"
                      aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>

              <div class="collapse navbar-collapse" id="navbarMenu">
                {% if user.is_authenticated %}
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle"
                       href="#" data-bs-toggle="dropdown"
                       aria-expanded="false">Menu</a>
                    <ul class="dropdown-menu">
                      <li><a class="dropdown-item" href="{% url 'tasks:add_category' %}">
                          {% trans 'Add Category' %}</a></li>
                      <li><a class="dropdown-item" href="{% url 'tasks:list_category' %}">
                          {% trans 'List Categories' %}</a></li>
                      <li><a class="dropdown-item" href="{% url 'tasks:add_task' %}">
                          {% trans 'Add Task' %}</a></li>
                      <li><a class="dropdown-item" href="{% url 'tasks:list_task' %}">
                          {% trans 'List Tasks' %}</a></li>
                      <li><a class="dropdown-item" href="{% url 'accounts:add_user' %}">
                          {% trans 'Add User' %}</a></li>
                    </ul>
                  </li>
                </ul>

                <form class="form-inline my-2 my-md-0" action="{% url 'core:search_tasks' %}" style="margin-right:10px" autocomplete="off">
                  <input class="form-control" name="query" type="text"
                         placeholder="{% trans 'Search a word' %}" aria-label="{% trans 'Search' %}"
                         style="margin-right:10px">
                  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">{% trans 'Search' %}</button>
                </form>
                {% endif %}

                {% if user.is_authenticated %}
                <ul class="navbar-nav mb-2 mb-lg-0">
                  <li class="nav-item">
                      {% if user.profile.photo %}
                      <img src="{{ user.profile.photo.url }}"
                           alt="{% trans 'Photo Profile' %}{{ user.get_full_name|default:user.username }}"
                           width="40" height="40"
                           class="rounded-circle"
                      >
                      {% else %}
                      <img src="{% static 'img/user.png' %}"
                           alt="{% trans 'Photo Profile' %}{{ user.get_full_name|default:user.username }}"
                           width="40" height="40"
                           class="rounded-circle"
                      >
                      {% endif %}
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle"
                       href="#" data-bs-toggle="dropdown"
                       aria-expanded="false">{{ user.get_full_name|default:user.username }}</a>
                    <ul class="dropdown-menu">
                      <li><a class="dropdown-item" href="{% url 'accounts:list_profile_user' %}">
                          {% trans 'Profile' %}</a></li>
                      <li><a class="dropdown-item" href="{% url 'accounts:change_password_user' %}">
                          {% trans 'Change Password' %}</a></li>
                      <li><a class="dropdown-item" href="{% url 'accounts:change_user' user.username %}">
                          {% trans 'Update User Informations' %}</a></li>
                      <li><a class="dropdown-item" href="/admin">
                          {% trans 'Admin' %}</a></li>
                      <li><a class="dropdown-item" href="{% url 'accounts:logout_user' %}">
                          {% trans 'Logout' %}</a></li>
                    </ul>
                  </li>
                </ul>
                {% endif %}
              </div>
            </div>
        </nav>

        {% block body %}

        {% endblock body %}

        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'js/jquery-3.6.1.min.js' %}"></script>
        <script src="{% static 'js/select2.min.js' %}"></script>
        <script src="{% static 'js/jquery.mask.min.js' %}"></script>
        <script src="{% static 'js/mask.js' %}"></script>
        <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>
        <script>
            $(document).on('click', '.confirm-delete', function () {
                $('#confirmDeleteModal').attr('caller-id', $(this).attr('id'));
            });
            $(document).on('click', '#confirmDeleteButtonModal', function () {
                const caller = $('#confirmDeleteButtonModal').closest('.modal').attr('caller-id');
                window.location = $('#'.concat(caller)).attr('href');
            });
            $(function() {
                $( "#id_end_date" ).datepicker(
                    {
                        dateFormat: "dd-mm-yy",
                        {#dayNamesMin: ["Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sáb"],#}
                        {#monthNames: ["Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho",#}
                        {#    "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro"],#}
                    }
                );
            });
            $(document).ready(function() {
                $('#id_category').select2();
            });
        </script>
    </body>
</html>