BestDjango/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.accounts import urls as accounts_urls
from apps.core import urls as core_urls
from apps.tasks import urls as tasks_urls
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(core_urls, namespace='core')),
    path('tasks/', include(tasks_urls, namespace='tasks')),
    path('accounts/', include(accounts_urls, namespace='accounts')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/tasks/urls.py
from django.urls import path
from . import views

app_name = 'tasks'

urlpatterns = [
    # Categories
    path('category/list', views.list_categories, name='list_category'),
    path('category/add', views.add_category, name='add_category'),
    path('category/edit/<int:id_category>/', views.edit_category, name='edit_category'),
    path('category/delete/<int:id_category>/', views.delete_category, name='delete_category'),
    # Tasks
    path('task/list', views.list_tasks, name='list_task'),
    path('task/add', views.add_task, name='add_task'),
    path('task/edit/<int:id_task>/', views.edit_task, name='edit_task'),
    path('task/delete/<int:id_task>/', views.delete_task, name='delete_task'),
]

apps/tasks/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import gettext_lazy as _


# Create your models here.
class Category(models.Model):
    name = models.CharField(_('Name'), max_length=150)
    description = models.TextField(_('Description'), blank=True, null=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name = _('Category')
        verbose_name_plural = _('Categories')
        ordering = ['id']

    def __str__(self):
        return '{} - {}'.format(self.id, self.name)


class Task(models.Model):
    PRIORITY_CHOICES = (
        ('L', _('LOW')),
        ('M', _('MEDIUM')),
        ('H', _('HIGH')),
    )
    STATUS_CHOICES = (
        ('I', _('IN PROGRESS')),
        ('P', _('PENDING')),
        ('C', _('COMPLETED')),
    )
    name = models.CharField(_('Name'), max_length=200)
    description = models.TextField(_('Description'))
    end_date = models.DateField(_('End Date'), auto_now=False, auto_now_add=False)
    priority = models.CharField(_('Priority'), max_length=1, choices=PRIORITY_CHOICES)
    category = models.ManyToManyField(Category)
    status = models.CharField(_('Status'), max_length=1, choices=STATUS_CHOICES)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name = _('Task')
        verbose_name_plural = _('Tasks')
        ordering = ['id']

    def __str__(self):
        return '{} - {}'.format(self.id, self.name)

    def list_categories(self):
        return ', '.join([cat.name for cat in self.category.all()])
    list_categories.short_description = _("Categories")

apps/tasks/forms.py
from django import forms

from .models import Task, Category


class CategoryForm(forms.ModelForm):

    class Meta:
        model = Category
        exclude = ('owner',)


class TaskForm(forms.ModelForm):

    class Meta:
        model = Task
        exclude = ('owner',)

apps/tasks/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.utils.translation import gettext_lazy as _

from .forms import CategoryForm, TaskForm
from .models import Category, Task


@login_required(login_url='/accounts/login-user')
def add_category(request) -> render:
    template_name = 'tasks/add_category.html'
    form = CategoryForm()

    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            f = form.save(commit=False)
            f.owner = request.user
            f.save()
            messages.success(request, _('Saved successfully!'))
            return redirect('tasks:list_category')
        messages.error(request, form.errors)

    context = {'form': form}
    return render(request, template_name, context)


@login_required(login_url='/accounts/login-user')
def list_categories(request) -> render:
    template_name = 'tasks/list_categories.html'
    context = {'categories': Category.objects.all()}
    return render(request, template_name, context)


@login_required(login_url='/accounts/login-user')
def edit_category(request, id_category) -> render or redirect:
    template_name = 'tasks/add_category.html'
    category = get_object_or_404(Category, pk=id_category, owner=request.user)
    form = CategoryForm(instance=category)

    if request.method == 'POST':
        form = CategoryForm(request.POST, instance=category)
        if form.is_valid():
            form.save()
            messages.success(request, _('Saved successfully!'))
            return redirect('tasks:list_category')
        messages.error(request, form.errors)

    context = {'form': form}
    return render(request, template_name, context)


@login_required(login_url='/accounts/login-user')
def delete_category(request, id_category) -> redirect:
    category = get_object_or_404(Category, pk=id_category, owner=request.user)
    category.delete()
    messages.success(request, _('Deleted successfully!'))
    return redirect('tasks:list_category')


@login_required(login_url='/accounts/login-user')
def add_task(request) -> render:
    template_name = 'tasks/add_task.html'
    form = TaskForm()

    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            f = form.save(commit=False)
            f.owner = request.user
            f.save()
            form.save_m2m()
            messages.success(request, _('Saved successfully!'))
            return redirect('tasks:list_tasks')
        messages.error(request, form.errors)

    context = {'form': form}
    return render(request, template_name, context)


@login_required(login_url='/accounts/login-user')
def list_tasks(request) -> render:
    template_name = 'tasks/list_tasks.html'
    context = {'tasks': Task.objects.filter(owner=request.user).exclude(status='C')}
    return render(request, template_name, context)


@login_required(login_url='/accounts/login-user')
def edit_task(request, id_task) -> render or redirect:
    template_name = 'tasks/add_task.html'
    task = get_object_or_404(Task, pk=id_task, owner=request.user)
    form = TaskForm(instance=task)

    if request.method == 'POST':
        if form.is_valid():
            form = TaskForm(request.POST, instance=task)
            form.save()
            messages.success(request, _('Saved successfully!'))
            return redirect('tasks:list_task')
        messages.error(request, form.errors)

    context = {'form': form}
    return render(request, template_name, context)


@login_required(login_url='/accounts/login-user')
def delete_task(request, id_task) -> redirect:
    task = get_object_or_404(Category, pk=id_task, owner=request.user)
    task.delete()
    messages.success(request, _('Deleted successfully!'))
    return redirect('tasks:list_task')

templates/tasks/add_category.html
{% extends 'base.html' %}
{% load i18n widget_tweaks %}

{% block title %}
    {% trans 'Add Category' %} - {{ block.super }}
{% endblock title %}

{% block body %}
    <div class="container">
        <h1>{% trans 'Add Category' %}</h1>
        {% include 'partials/messages.html' %}
        <div class="row">
            <div class="col-md-12">
                <form action="." method="post">
                    {% csrf_token %}

                    <div class="mb-3">
                        <label for="{{ form.name.id_for_label }}" class="form-label">
                            {% trans 'Name' %}
                        </label>
                        {{ form.name|add_class:"form-control"|attr:"autofocus" }}
                    </div>
                    <div class="mb-3">
                        <label for="{{ form.name.id_for_label }}" class="form-label">
                            {% trans 'Description' %}
                        </label>
                        {{ form.description|add_class:"form-control"  }}
                    </div>

                    <button type="submit" class="btn btn-primary">{% trans 'Save' %}</button>
                </form>
            </div>
        </div>
    </div>

{% endblock body %}

templates/tasks/add_task.html
{% extends 'base.html' %}
{% load i18n widget_tweaks %}

{% block title %}
    {% trans 'Add Task' %} - {{ block.super }}
{% endblock title %}

{% block body %}
    <div class="container">
        <h1>{% trans 'Add Task' %}</h1>
        {% include 'partials/messages.html' %}
        <div class="row">
            <div class="col-md-12">
                <form action="." method="post">
                    {% csrf_token %}

                    <div class="mb-3">
                        <label for="{{ form.name.id_for_label }}" class="form-label">
                            {% trans 'Name' %}
                        </label>
                        {{ form.name|add_class:"form-control"|attr:"autofocus" }}
                    </div>
                    <div class="mb-3">
                        <label for="{{ form.name.id_for_label }}" class="form-label">
                            {% trans 'Description' %}
                        </label>
                        {{ form.description|add_class:"form-control"  }}
                    </div>
                    <div class="mb-3">
                        <label for="{{ form.end_date.id_for_label }}" class="form-label">
                            {% trans 'End Date' %}
                        </label>
                        {{ form.end_date|add_class:"form-control"  }}
                    </div>
                    <div class="mb-3">
                        <label for="{{ form.priority.id_for_label }}" class="form-label">
                            {% trans 'Priority' %}
                        </label>
                        {{ form.priority|add_class:"form-control"  }}
                    </div>
                    <div class="mb-3">
                        <label for="{{ form.category.id_for_label }}" class="form-label">
                            {% trans 'Category' %}
                        </label>
                        {{ form.category|add_class:"form-control"  }}
                    </div>
                    <div class="mb-3">
                        <label for="{{ form.status.id_for_label }}" class="form-label">
                            {% trans 'Status' %}
                        </label>
                        {{ form.status|add_class:"form-control"  }}
                    </div>

                    <button type="submit" class="btn btn-primary">{% trans 'Save' %}</button>
                </form>
            </div>
        </div>
    </div>

{% endblock body %}

templates/tasks/list_categories.html
{% extends 'base.html' %}
{% load i18n widget_tweaks %}

{% block title %}
    {% trans 'List Categories' %} - {{ block.super }}
{% endblock title %}

{% block body %}
    <div class="container">
        <h1>{% trans 'List Categories' %}</h1>
        {% include 'partials/messages.html' %}
        <div class="row">
            <div class="col-md-12">
                <table class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">{% trans 'Category' %}</th>
                            <th scope="col">{% trans 'Description' %}</th>
                            <th scope="col">{% trans 'Actions' %}</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for category in categories %}
                        <tr>
                            <th scope="row">{{ category.id }}</th>
                            <td>{{ category.name }}</td>
                            <td>{{ category.description }}</td>
                            <td>
                                <a href="{% url 'tasks:edit_category' category.id %}" class="btn btn-primary btn-sm">
                                    {% trans 'Edit' %}</a>
                                <a
                                    href="{% url 'tasks:delete_category' category.id %}"
                                    class="btn btn-danger btn-sm confirm-delete"
                                    data-bs-toggle="modal"
                                    data-bs-target="#confirmDeleteModal"
                                    id="deleteButton-{{ category.id }}"
                                >
                                    {% trans 'Delete' %}</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        {% include 'partials/confirm_delete_modal.html' %}
    </div>

{% endblock body %}

templates/tasks/list_tasks.html
{% extends 'base.html' %}
{% load i18n widget_tweaks %}

{% block title %}
    {% trans 'List Tasks' %} - {{ block.super }}
{% endblock title %}

{% block body %}
    <div class="container">
        <h1>{% trans 'List Tasks' %}</h1>
        {% include 'partials/messages.html' %}
        <div class="row">
            <div class="col-md-12">
                <table class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">{% trans 'Task' %}</th>
                            <th scope="col">{% trans 'Description' %}</th>
                            <th scope="col">{% trans 'End Date' %}</th>
                            <th scope="col">{% trans 'Priority' %}</th>
                            <th scope="col">{% trans 'Category' %}</th>
                            <th scope="col">{% trans 'Status' %}</th>
                            <th scope="col">{% trans 'Actions' %}</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for task in tasks %}
                        <tr>
                            <th scope="row">{{ task.id }}</th>
                            <td>{{ task.name }}</td>
                            <td>{{ task.description }}</td>
                            <td>{{ task.end_date }}</td>
                            <td>{{ task.get_priority_display }}</td>
                            <td>
                                {% for category in task.category.all %}
                                    {{ category }} {% if task.category.all.count > forloop.counter %} | {% endif %}
                                {% endfor %}
                            </td>
                            <td>{{ task.get_status_display }}</td>
                            <td>
                                <a href="{% url 'tasks:edit_task' task.id %}" class="btn btn-primary btn-sm">
                                    {% trans 'Edit' %}</a>
                                <a
                                    href="{% url 'tasks:delete_task' task.id %}"
                                    class="btn btn-danger btn-sm confirm-delete"
                                    data-bs-toggle="modal"
                                    data-bs-target="#confirmDeleteModal"
                                    id="deleteButton-{{ task.id }}"
                                >
                                    {% trans 'Delete' %}</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        {% include 'partials/confirm_delete_modal.html' %}
    </div>

{% endblock body %}